name: Run Linter on Reporting App

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install Python dependencies
        run: pip install -r reqs/requirements-test.txt

      - name: Run Black
        run: |
          python -m black \
              -t py310 \
              --check app tests

      - name: Run Isort
        run: |
          python -m isort \
            --df --settings-path=.isort.cfg \
            --check app tests 

      - name: Run Flake8
        run: python -m flake8 app tests 
