name: Run Tests

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip \
            && pip install -r reqs/requirements.txt \
              -r reqs/requirements-test.txt

      - name: Run Tests
        run: python -m pytest tests
